sudo: false
language: ruby
cache: bundler
services:
  - redis-server
bundler_args: "--without production development"
before_script:
  - "cp config/.env.travis config/.env.test"
  - "mysql -e 'create database mconf_test;'"
  - "cp config/setup_conf.yml.example config/setup_conf.yml"
script: bundle exec rake
rvm:
  - 2.2.5
