version: '2.4'
services:

  dev:
    container_name: mconf_web_ufrgs_dev
    build: .
    image: mconf_web_ufrgs_dev:dev
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - dev_db
      - dev_redis
    env_file:
      - ./.env
      - ./.env.development
      - ./.env.development.local
    volumes:
      - ./:/usr/src/app
      - bundle-volume:/usr/src/bundle
    command: bash -c "rm -f tmp/pids/server.pid && script/rails s -p3000"
  dev_db:
    container_name: mconf_web_ufrgs_dev_db
    image: mysql:5.6
    expose:
      - "3306"
    volumes:
      - dev-db-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mconf
      - MYSQL_DATABASE=mconf_web_dev
      - MYSQL_USER=mconf
      - MYSQL_PASSWORD=mconf
  dev_redis:
    container_name: mconf_web_ufrgs_dev_redis
    image: redis:3.2
    expose:
      - "6379"
    command: redis-server --requirepass "XYqZihWYGeAIOZo2VN2LcNJxC2R4UcQE"


  #
  # Mailcatcher and its dependencies to test emails in development
  #

  dev_mailer:
    container_name: mconf_web_ufrgs_dev_mailer
    image: mconf_web_ufrgs_dev:dev
    ports:
      - "1080:1080"
      - "1025:1025"
    depends_on:
      - dev_resque_worker
      - dev_resque_scheduler
    env_file:
      - ./.env
      - ./.env.development
    volumes:
      - ./:/usr/src/app
      - bundle-volume:/usr/src/bundle
    command: bash -c "bundle exec mailcatcher --ip=0.0.0.0 -f"

  dev_resque_worker:
    container_name: mconf_web_ufrgs_dev_resque_worker
    image: mconf_web_ufrgs_dev:dev
    depends_on:
      - dev_db
      - dev_redis
    env_file:
      - ./.env
      - ./.env.development
    environment:
      - QUEUE=*
    volumes:
      - ./:/usr/src/app
      - bundle-volume:/usr/src/bundle
    command: bash -c "bundle exec rake resque:work"

  dev_resque_scheduler:
    container_name: mconf_web_ufrgs_dev_resque_scheduler
    image: mconf_web_ufrgs_dev:dev
    depends_on:
      - dev_db
      - dev_redis
    env_file:
      - ./.env
      - ./.env.development
    volumes:
      - ./:/usr/src/app
      - bundle-volume:/usr/src/bundle
    command: bash -c "bundle exec rake resque:scheduler"


  test:
    container_name: mconf_web_ufrgs_test
    build: .
    tty: true
    stdin_open: true
    depends_on:
      - test_db
      - test_redis
    env_file:
      - ./.env
      - ./.env.test
    volumes:
      - ./:/usr/src/app
      - bundle-volume:/usr/src/bundle
    command: bash -c "bundle exec rake"
  test_db:
    container_name: mconf_web_ufrgs_test_db
    image: mysql:5.6
    expose:
      - "3306"
    volumes:
      - test-db-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mconf
      - MYSQL_DATABASE=mconf_web_ufrgs_test
      - MYSQL_USER=mconf
      - MYSQL_PASSWORD=mconf
  test_redis:
    container_name: mconf_web_ufrgs_test_redis
    image: redis:3.2
    expose:
      - "6379"
    command: redis-server --requirepass "XYqZihWYGeAIOZo2VN2LcNJxC2R4UcQE"

volumes:
  dev-db-volume:
  test-db-volume:
  bundle-volume:
