# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.

development:
  adapter:  <%= ENV['MCONF_DATABASE_DEV_ADAPTER'] || 'mysql2' %>
  host:     <%= ENV['MCONF_DATABASE_DEV_HOST'] || 'dev_db' %>
  database: <%= ENV['MCONF_DATABASE_DEV_NAME'] || 'mconf_web_dev' %>
  username: <%= ENV['MCONF_DATABASE_DEV_USERNAME'] %>
  password: <%= ENV['MCONF_DATABASE_DEV_PASSWORD'] %>
  socket:   <%= ENV['MCONF_DATABASE_DEV_SOCKET'] || '/var/run/mysqld/mysqld.sock' %>

test:
  adapter:  <%= ENV['MCONF_DATABASE_TEST_ADAPTER'] || 'mysql2' %>
  host:     <%= ENV['MCONF_DATABASE_TEST_HOST'] || '127.0.0.1' %>
  database: <%= ENV['MCONF_DATABASE_TEST_NAME'] %>_<%= ENV['TEST_ENV_NUMBER'] %>
  username: <%= ENV['MCONF_DATABASE_TEST_USERNAME'] %>
  password: <%= ENV['MCONF_DATABASE_TEST_PASSWORD'] %>
  socket:   <%= ENV['MCONF_DATABASE_TEST_SOCKET'] || '/var/run/mysqld/mysqld.sock' %>

production:
  adapter:  <%= ENV['MCONF_DATABASE_PROD_ADAPTER'] || 'mysql2' %>
  host:     <%= ENV['MCONF_DATABASE_PROD_HOST'] || '127.0.0.1' %>
  database: <%= ENV['MCONF_DATABASE_PROD_NAME'] || 'mconf_web_production' %>
  username: <%= ENV['MCONF_DATABASE_PROD_USERNAME'] %>
  password: <%= ENV['MCONF_DATABASE_PROD_PASSWORD'] %>
  socket:   <%= ENV['MCONF_DATABASE_PROD_SOCKET'] || '/var/run/mysqld/mysqld.sock' %>
